  CreateOrUpdateEndpointLambda:
    Type: AWS::Lambda::Function
    Properties: 
      Code: lambda/create_or_update_endpoint.py
      Description: "Lambda that creates or updates a SageMaker endpoint."
      Environment: 
        Variables: 
          ENDPOINT_NAME: !Join
            - '-'
            - - !Ref EnvironmentName
              - !Ref ProductName
              - !Ref ServiceName
          PRODUCT_TAG_VALUE: !Ref ProductName
          SERVICE_TAG_VALUE: !Ref ServiceName
          STAGE_TAG_VALUE:  !Ref EnvironmentName
      FunctionName: !Join
        - '-'
        - - !Ref EnvironmentName
          - !Ref ProductName
          - !Ref ServiceName
          - update-endpoint
      Handler: create_or_update_endpoint.lambda_handler
      Role: !GetAtt SagemakerLambdaRole.Arn
      Runtime: "python3.7"
      Tags: 
        - 
          Key: "product"
          Value: !Ref ProductName
        - 
          Key: "service"
          Value: !Ref ServiceName
        - 
          Key: "stage"
          Value: !Ref EnvironmentName
  CheckEndpointStatusLambda:
    Type: AWS::Lambda::Function
    Properties: 
      Code: lambda/check_endpoint_status.py
      Description: "Lambda that checks the status of a SageMaker endpoint"
      Environment: 
        Variables: 
          ENDPOINT_NAME: !Join
            - '-'
            - - !Ref EnvironmentName
              - !Ref ProductName
              - !Ref ServiceName
      FunctionName: !Join
        - '-'
        - - !Ref EnvironmentName
          - !Ref ProductName
          - !Ref ServiceName
          - get-endpoint-status
      Handler: check_endpoint_status.lambda_handler
      Role: !GetAtt SagemakerLambdaRole.Arn
      Runtime: "python3.7"
      Tags: 
        - 
          Key: "product"
          Value: !Ref ProductName
        - 
          Key: "service"
          Value: !Ref ServiceName
        - 
          Key: "stage"
          Value: !Ref EnvironmentName
  TrainAndDeployStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties: 
      DefinitionString: !Sub 
        - |
          {
            "Comment": "Training and deployment pipeline for a Machine Learning model.",
            "StartAt": "Try",
            "States": {
              "Try": {
                "Type": "Parallel",
                "Branches": [
                  {
                    "StartAt": "Create Training Job Parameters",
                    "States": {
                      "Create Training Job Parameters": {
                        "Type": "Task",
                        "Parameters": {
                          "execution_name.$":"$$.Execution.Name",
                          "input.$":"$"
                        },
                        "Resource": "${CreateTrainingJobLambdaArn}",
                        "ResultPath": "$.PreviousStep",
                        "Next": "Execute Training Job"
                      },
                      "Execute Training Job": {
                        "Type":"Task",
                        "Resource":"arn:aws:states:::sagemaker:createTrainingJob.sync",
                        "Parameters": {
                          "TrainingJobName.$": "$.PreviousStep.TrainingJobParameters.TrainingJobName",
                          "AlgorithmSpecification.$": "$.PreviousStep.TrainingJobParameters.AlgorithmSpecification",
                          "RoleArn.$": "$.PreviousStep.TrainingJobParameters.RoleArn",
                          "InputDataConfig.$": "$.PreviousStep.TrainingJobParameters.InputDataConfig",
                          "OutputDataConfig.$": "$.PreviousStep.TrainingJobParameters.OutputDataConfig",
                          "ResourceConfig.$": "$.PreviousStep.TrainingJobParameters.ResourceConfig",
                          "StoppingCondition.$": "$.PreviousStep.TrainingJobParameters.StoppingCondition",
                          "EnableNetworkIsolation.$": "$.PreviousStep.TrainingJobParameters.EnableNetworkIsolation",
                          "Tags.$": "$.PreviousStep.TrainingJobParameters.Tags"
                        },
                        "ResultPath": "$.PreviousStep",
                        "Next": "Get Training Job Metrics"
                      },
                      "Get Training Job Metrics": {
                        "Type": "Task",
                        "Resource": "${CheckTrainingJobStatusLambdaArn}",
                        "ResultPath": "$.PreviousStep",
                        "Next": "Check Model Metrics"
                      },
                      "Check Model Metrics": {
                        "Type": "Choice",
                        "Choices": [
                          {
                            "Variable": "$.PreviousStep.Metrics.Scoring-Metric",
                            "NumericGreaterThan": 50,
                            "Next": "Is Feature Branch"
                          }
                        ],
                        "Default": "NotifyError"
                      },
                      "Is Feature Branch": {
                        "Type": "Choice",
                        "Choices": [
                          {
                            "Variable": "$.ecr.repository_name",
                            "StringEquals": "${StagingEcrRepoName}",
                            "Next": "Success"
                          }
                        ],
                        "Default": "Create Model"
                      },
                      "Create Model": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::sagemaker:createModel",
                        "Parameters": {                  
                          "ExecutionRoleArn": "${SageMakerExecutionRoleArn}",
                          "ModelName.$": "$$.Execution.Name",
                          "PrimaryContainer": { 
                              "Image.$": "$.PreviousStep.AlgorithmSpecification.TrainingImage",
                              "ModelDataUrl.$": "$.PreviousStep.ModelArtifacts.S3ModelArtifacts"
                          },
                          "Tags": [ 
                              { 
                                "Key": "product",
                                "Value": "${ProductTagValue}"
                              },
                              { 
                                "Key": "service",
                                "Value": "${ServiceTagValue}"
                              },
                              { 
                                "Key": "stage",
                                "Value": "${StageTagValue}"
                              }
                          ]
                        },
                        "ResultPath": "$.PreviousStep",
                        "Next": "Create Endpoint Config"
                      },
                      "Create Endpoint Config": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::sagemaker:createEndpointConfig",
                        "Parameters": {
                          "EndpointConfigName.$": "$$.Execution.Name",
                          "ProductionVariants": [ 
                              { 
                                "InitialInstanceCount": 1,
                                "InitialVariantWeight": 1,
                                "InstanceType.$": "$.sagemaker.EndpointConfig.InstanceType",
                                "ModelName.$": "$$.Execution.Name",
                                "VariantName": "AllTraffic"
                              }
                          ],
                          "Tags": [ 
                              { 
                                "Key": "product",
                                "Value": "${ProductTagValue}"
                              },
                              { 
                                "Key": "service",
                                "Value": "${ServiceTagValue}"
                              },
                              { 
                                "Key": "stage",
                                "Value": "${StageTagValue}"
                              }
                          ]
                        },
                        "ResultPath": "$.PreviousStep",
                        "Next": "Create or Update Endpoint"
                      },
                      "Create or Update Endpoint": {
                        "Type": "Task",
                        "Parameters": {
                          "endpoint_config_name.$":"$$.Execution.Name",
                          "input.$":"$"
                        },
                        "Resource": "${CreateOrUpdateEndpointLambdaArn}",
                        "ResultPath": "$.PreviousStep",
                        "Next": "Wait 30 Seconds"
                      },
                      "Wait 30 Seconds": {
                        "Type": "Wait",
                        "Seconds": 30,
                        "Next": "Get Endpoint Status"
                      },
                      "Get Endpoint Status": {
                        "Type": "Task",
                        "Resource": "${CheckEndpointStatusLambdaArn}",
                        "ResultPath": "$.PreviousStep",
                        "Next": "Endpoint Status"
                      },
                      "Endpoint Status": {
                        "Type": "Choice",
                        "Choices": [
                          {
                            "Or": [
                              {
                                "Variable": "$.PreviousStep.EndpointStatus",
                                "StringEquals": "Creating"
                              },
                              {
                                "Variable": "$.PreviousStep.EndpointStatus",
                                "StringEquals": "Updating"
                              }
                            ],
                            "Next": "Wait 30 Seconds"
                          },
                          {
                            "Variable": "$.PreviousStep.EndpointStatus",
                            "StringEquals": "InService",
                            "Next": "Success"
                          }
                        ],
                        "Default": "NotifyError"
                      },
                      "NotifyError": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::sns:publish",
                        "Parameters": {
                          "TopicArn": "${PipelineStatusSnsTopicArn}",
                          "Message": "FAILURE",
                          "MessageAttributes": {
                            "StepFunctionsExecutionName": {
                              "DataType": "String",
                              "StringValue.$": "$$.Execution.Name"
                            },
                            "GitCommitHash": {
                              "DataType": "String",
                              "StringValue.$": "$.ecr.image_tags[0]"
                            },
                            "DataVersion": {
                              "DataType": "String",
                              "StringValue.$": "$.s3.version"
                            }
                          }
                        },
                        "ResultPath": "$.PreviousStep",
                        "Next": "Fail"
                      },
                      "Fail": {
                        "Type": "Fail"
                      },
                      "Success": {
                        "Type": "Pass",
                        "End": true
                      }
                    }
                  }
                ],
                "Catch": [
                  {
                    "ErrorEquals": [ "States.ALL" ],
                    "ResultPath": "$.PreviousStep",
                    "Next": "ExceptionNotifyError"
                  }
                ],
                "Next": "UnwrapOutput"
              },
              "ExceptionNotifyError": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${PipelineStatusSnsTopicArn}",
                  "Message": "FAILURE",
                  "MessageAttributes": {
                    "StepFunctionsExecutionName": {
                      "DataType": "String",
                      "StringValue.$": "$$.Execution.Name"
                    },
                    "GitCommitHash": {
                      "DataType": "String",
                      "StringValue.$": "$.ecr.image_tags[0]"
                    },
                    "DataVersion": {
                      "DataType": "String",
                      "StringValue.$": "$.s3.version"
                    }
                  }
                },
                "ResultPath": "$.PreviousStep",
                "Next": "ExceptionFail"
              },
              "ExceptionFail": {
                "Type": "Fail"
              },
              "UnwrapOutput": {
                "Type": "Pass",
                "InputPath": "$[0]", 
                "Next": "NotifySuccess"
              },
              "NotifySuccess": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${PipelineStatusSnsTopicArn}",
                  "Message": "SUCCESS",
                  "MessageAttributes": {
                    "StepFunctionsExecutionName": {
                      "DataType": "String",
                      "StringValue.$": "$$.Execution.Name"
                    },
                    "GitCommitHash": {
                      "DataType": "String",
                      "StringValue.$": "$.ecr.image_tags[0]"
                    },
                    "DataVersion": {
                      "DataType": "String",
                      "StringValue.$": "$.s3.version"
                    }
                  }
                },
                "ResultPath": "$.PreviousStep",
                "Next": "Succeed"
              },
              "Succeed": {
                "Type": "Succeed"
              } 
            }
          }
        - { 
            CreateTrainingJobLambdaArn: !GetAtt CreateTrainingJobLambda.Arn,
            CheckTrainingJobStatusLambdaArn: !GetAtt CheckTrainingJobStatusLambda.Arn,
            SageMakerExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn,
            ProductTagValue: !Ref ProductName,
            ServiceTagValue: !Ref ServiceName,
            StageTagValue: !Ref EnvironmentName,
            CreateOrUpdateEndpointLambdaArn: !GetAtt CreateOrUpdateEndpointLambda.Arn,
            CheckEndpointStatusLambdaArn: !GetAtt CheckEndpointStatusLambda.Arn,
            PipelineStatusSnsTopicArn: !Ref PipelineStatusSnsTopic,
            StagingEcrRepoName: !Ref StagingEcrRepository
          }
      RoleArn: !GetAtt TrainAndDeployStepFunctionsRole.Arn
      StateMachineName: !Join
        - '-'
        - - !Ref EnvironmentName
          - !Ref ProductName
          - !Ref ServiceName
          - train-deploy
      Tags: 
        - 
          Key: "product"
          Value: !Ref ProductName
        - 
          Key: "service"
          Value: !Ref ServiceName
        - 
          Key: "stage"
          Value: !Ref EnvironmentName